// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: connect/message/message.proto

package data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessType int32

const (
	MessType_UNKNOW    MessType = 0
	MessType_EVENT     MessType = 1
	MessType_CLIPBROAD MessType = 2
	MessType_AUTH      MessType = 3
	MessType_KEEPALIVE MessType = 4
	MessType_REGISTER  MessType = 5
	MessType_ENTER     MessType = 6 // start to control remote
	MessType_RELEASE   MessType = 7 // stop control remote
)

// Enum value maps for MessType.
var (
	MessType_name = map[int32]string{
		0: "UNKNOW",
		1: "EVENT",
		2: "CLIPBROAD",
		3: "AUTH",
		4: "KEEPALIVE",
		5: "REGISTER",
		6: "ENTER",
		7: "RELEASE",
	}
	MessType_value = map[string]int32{
		"UNKNOW":    0,
		"EVENT":     1,
		"CLIPBROAD": 2,
		"AUTH":      3,
		"KEEPALIVE": 4,
		"REGISTER":  5,
		"ENTER":     6,
		"RELEASE":   7,
	}
)

func (x MessType) Enum() *MessType {
	p := new(MessType)
	*p = x
	return p
}

func (x MessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessType) Descriptor() protoreflect.EnumDescriptor {
	return file_connect_message_message_proto_enumTypes[0].Descriptor()
}

func (MessType) Type() protoreflect.EnumType {
	return &file_connect_message_message_proto_enumTypes[0]
}

func (x MessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessType.Descriptor instead.
func (MessType) EnumDescriptor() ([]byte, []int) {
	return file_connect_message_message_proto_rawDescGZIP(), []int{0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       bool                   `protobuf:"varint,1,opt,name=Request,proto3" json:"Request,omitempty"` // defalt = false
	Type          MessType               `protobuf:"varint,2,opt,name=Type,proto3,enum=message.MessType" json:"Type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=Payload,proto3" json:"Payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_connect_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_connect_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_connect_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetRequest() bool {
	if x != nil {
		return x.Request
	}
	return false
}

func (x *Message) GetType() MessType {
	if x != nil {
		return x.Type
	}
	return MessType_UNKNOW
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Code          int32                  `protobuf:"varint,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_connect_message_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_connect_message_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_connect_message_message_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Event) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Event) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type ClipBroad struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipBroad) Reset() {
	*x = ClipBroad{}
	mi := &file_connect_message_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipBroad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipBroad) ProtoMessage() {}

func (x *ClipBroad) ProtoReflect() protoreflect.Message {
	mi := &file_connect_message_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipBroad.ProtoReflect.Descriptor instead.
func (*ClipBroad) Descriptor() ([]byte, []int) {
	return file_connect_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *ClipBroad) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Nonce         string                 `protobuf:"bytes,2,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=Method,proto3" json:"Method,omitempty"`
	Result        []byte                 `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_connect_message_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_connect_message_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_connect_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *Auth) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Auth) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *Auth) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Auth) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_connect_message_message_proto protoreflect.FileDescriptor

const file_connect_message_message_proto_rawDesc = "" +
	"\n" +
	"\x1dconnect/message/message.proto\x12\amessage\"d\n" +
	"\aMessage\x12\x18\n" +
	"\aRequest\x18\x01 \x01(\bR\aRequest\x12%\n" +
	"\x04Type\x18\x02 \x01(\x0e2\x11.message.MessTypeR\x04Type\x12\x18\n" +
	"\aPayload\x18\x03 \x01(\fR\aPayload\"E\n" +
	"\x05Event\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\x05R\x04Type\x12\x12\n" +
	"\x04Code\x18\x02 \x01(\x05R\x04Code\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\x05R\x05Value\"\x1f\n" +
	"\tClipBroad\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data\"`\n" +
	"\x04Auth\x12\x12\n" +
	"\x04User\x18\x01 \x01(\tR\x04User\x12\x14\n" +
	"\x05Nonce\x18\x02 \x01(\tR\x05Nonce\x12\x16\n" +
	"\x06Method\x18\x03 \x01(\tR\x06Method\x12\x16\n" +
	"\x06result\x18\x04 \x01(\fR\x06result*o\n" +
	"\bMessType\x12\n" +
	"\n" +
	"\x06UNKNOW\x10\x00\x12\t\n" +
	"\x05EVENT\x10\x01\x12\r\n" +
	"\tCLIPBROAD\x10\x02\x12\b\n" +
	"\x04AUTH\x10\x03\x12\r\n" +
	"\tKEEPALIVE\x10\x04\x12\f\n" +
	"\bREGISTER\x10\x05\x12\t\n" +
	"\x05ENTER\x10\x06\x12\v\n" +
	"\aRELEASE\x10\aB\bZ\x06./datab\x06proto3"

var (
	file_connect_message_message_proto_rawDescOnce sync.Once
	file_connect_message_message_proto_rawDescData []byte
)

func file_connect_message_message_proto_rawDescGZIP() []byte {
	file_connect_message_message_proto_rawDescOnce.Do(func() {
		file_connect_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_connect_message_message_proto_rawDesc), len(file_connect_message_message_proto_rawDesc)))
	})
	return file_connect_message_message_proto_rawDescData
}

var file_connect_message_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_connect_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_connect_message_message_proto_goTypes = []any{
	(MessType)(0),     // 0: message.MessType
	(*Message)(nil),   // 1: message.Message
	(*Event)(nil),     // 2: message.Event
	(*ClipBroad)(nil), // 3: message.ClipBroad
	(*Auth)(nil),      // 4: message.Auth
}
var file_connect_message_message_proto_depIdxs = []int32{
	0, // 0: message.Message.Type:type_name -> message.MessType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_connect_message_message_proto_init() }
func file_connect_message_message_proto_init() {
	if File_connect_message_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_connect_message_message_proto_rawDesc), len(file_connect_message_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_connect_message_message_proto_goTypes,
		DependencyIndexes: file_connect_message_message_proto_depIdxs,
		EnumInfos:         file_connect_message_message_proto_enumTypes,
		MessageInfos:      file_connect_message_message_proto_msgTypes,
	}.Build()
	File_connect_message_message_proto = out.File
	file_connect_message_message_proto_goTypes = nil
	file_connect_message_message_proto_depIdxs = nil
}
